metamodels.content-article:
  path: /contao/metamodel/{tableName}/{itemId}/content-article/{attribute}
  defaults:
    _controller: MetaModels\AttributeContentArticleBundle\Controller\Backend\MetaModelController
    _scope: backend
    _store_referrer: true
#    _contao_referer_id: true
    _token_check: true
