services:
    MetaModels\AttributeContentArticleBundle\Attribute\AttributeTypeFactory:
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
            - { name: metamodels.attribute_factory }

    MetaModels\AttributeContentArticleBundle\EventListener\BackendEventListener:
      public: true
      arguments:
        - '@database_connection'

    MetaModels\AttributeContentArticleBundle\Controller\Backend\MetaModelController:
      tags: ['controller.service_arguments']
