services:
    MetaModels\AttributeContentArticleBundle\Attribute\AttributeTypeFactory:
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
            - { name: metamodels.attribute_factory }
    MetaModels\AttributeContentArticleBundle\Table\ArticleContent:
      public: true
      arguments:
        - '@database_connection'
        - '@session'
    MetaModels\AttributeContentArticleBundle\EventListener\BackendEventListener:
      public: true
      arguments:
        - '@database_connection'
