services:
    MetaModels\AttributeContentArticleBundle\Attribute\AttributeTypeFactory:
        arguments:
            - '@event_dispatcher'
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
            - { name: metamodels.attribute_factory }