services:
    MetaModels\AttributeContentArticleBundle\Attribute\AttributeTypeFactory:
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
            - { name: metamodels.attribute_factory }
    MetaModels\AttributeContentArticleBundle\Table\ArticleContent:
      arguments:
        - '@database_connection'
    MetaModels\AttributeContentArticleBundle\EventListener\BackendEventListener:
      arguments:
        - '@database_connection'
